### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by dawncc** [dawncc/TensorFlowTest#3]
# [Jupyter Notebook](http://jupyter.org/)
## 安装
```python
pip install jupyter
```
版本不支持错误：
``` python
    Complete output from command python setup.py egg_info:
    
    IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Beginning with IPython 6.0, Python 3.3 and above is required.
    
    See IPython `README.rst` file for more information:
    
        https://github.com/ipython/ipython/blob/master/README.rst
    
    Python sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0) detected.
    
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TXUqxq/ipython/

```

**Comment by dawncc** [comment]
# 安装python3.6
## 1. 下载python3.6源码
```python
# wget http://mirrors.sohu.com/python/3.6.0/Python-3.6.0.tar.xz
```
## 2. 解压缩并安装
```python
# xz -d Python-3.6.0.tar.xz
# tar xf Python-3.6.0.tar
# ./configure --prefix=/usr/local/python36
# make -j8 && make install
```
## 3. 修改系统默认的Python路径，
```python
# 终端中输入Python命令时默认是指向Python2.7
mv /usr/bin/python /usr/bin/python-2.7
#建立新的软连接，指向Python-3.6.0： 
ln -s /usr/local/python36/bin/python3.6 /usr/bin/python
```
## 4. upyter notebook command not found
```
export PATH=$PATH:/usr/local/python36/bin
```
## 5.安装pip3
```
apt install python3-pip
```
## 6. ModuleNotFoundError: No module named '_sqlite3'
```
sudo apt-get install libsqlite3-dev
pip install pysqlite
python manager.py syncdb
```
## 安装jupyter
```
pip3 install jupyter
```

**Comment by dawncc** [comment]
# yum
```
apt install yum
```
# Zlib
```
sudo apt-get install zlib1g-dev
```

**Comment by dawncc** [comment]
# 用virtualenv管理python3运行环境
## 1. 安装
```
sudo pip install virtualenv
sudo pip install virtualenvwrapper
```
在~/.bashrc里面加上：
```
export WORKON_HOME=/home/dev/virtualenv  #你创建的虚拟环境所放置的目录
source /usr/local/bin/virtualenvwrapper.sh
```

**Comment by dawncc** [comment]
# 启动 jupyter
```
jupyter notebook
```

- *报错1：*

```python
[I 21:49:47.578 NotebookApp] Writing notebook server cookie secret to /run/user/0/jupyter/notebook_cookie_secret
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1120, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/local/lib/python3.5/dist-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.5/dist-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```
使用如下命令执行,绑定本机IP
```python
jupyter notebook --ip=127.0.0.1

```

- *报错2：*
```
[C 21:52:37.194 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
```
开启使用root用户权限
```python
jupyter notebook --ip=***.**.**.* --allow-root
```
![image](https://cloud.githubusercontent.com/assets/3145825/26157775/a3964196-3b4c-11e7-9018-4c303c558be6.png)

**Comment by dawncc** [comment]
![image](https://cloud.githubusercontent.com/assets/3145825/26158344/2352edf2-3b4e-11e7-9f23-7b07c2086475.png)
